MODULAR_TASKS = {
    "status_query": ("tasks.status_query", "frame_status_query"),
    "claim_identification": ("tasks.claim_identification", "frame_claim_identification"),
    "attackers_of": ("tasks.attackers_of", "frame_attackers_of"),
    "enthymeme": ("tasks.enthymeme", "frame_enthymeme"),
    "attack": ("tasks.attack", "frame_attack"),
    "counter_argumentation": ("tasks.counter_argumentation", "frame_counter_argumentation"),
    "preference_construction": ("tasks.preference_construction", "frame_preference_construction"),
    "formalization": ("tasks.formalization", "frame_formalization"),
    "perturbation_prediction": ("tasks.perturbation_prediction", "frame_perturbation_prediction"),
    "robustness": ("tasks.robustness", "frame_robustness"),
    "syntax": ("tasks.syntax", "frame_syntax"),
    "evidence_construction": ("tasks.evidence_construction", "frame_evidence_construction"),
    "ordering_sensitivity": ("tasks.ordering_sensitivity", "frame_ordering_sensitivity"),
}
