"""Generated items must be answerable from what the prompt actually says.

validate_entry checks gold against the engine but never inspects the prompt, so
an item can be internally consistent, self-score 1.0, and still be unanswerable.
These are the cases where that happened.
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from aspic_gym import create_dataset, score_answer, validate_entry  # noqa: E402

_RULE_LITERAL_CLAIM = re.compile(r"^\s*\d+\.\s*-?[ds]\d+\s*$", re.M)


def test_content_claims_are_never_raw_rule_symbols():
    """Content mode displays rules as "Rule k", so a claim like `-d28` names
    something the prompt never defines -- and it appeared in gold answers."""
    for level in (5, 15):
        ds = create_dataset("claim_identification", size=3, level=level,
                            seed=1, with_content=True)
        for i in range(3):
            claims = re.search(r"Claims:\n(.*?)(?=\n\n|\Z)",
                               ds[i]["question"], re.S)
            assert claims, "claim_identification prompt has no Claims block"
            assert not _RULE_LITERAL_CLAIM.search(claims.group(1)), (
                f"raw rule literal offered as a claim at level {level}:\n"
                + claims.group(1))


def test_no_literal_is_both_axiom_and_ordinary_premise():
    """Axioms are unattackable and ordinary premises are attackable, so a
    literal declared as both is contradictory. Level 3 produced this for every
    item, because the premise top-up always returned the symbol `a0`."""
    for level in (1, 3, 5):
        ds = create_dataset("formalization", size=3, level=level,
                            seed=1, with_content=False)
        for i in range(3):
            ops = ds[i]["metadata"]["ops"]
            axioms = {o.get("content") for o in ops if o.get("kind") == "axiom"}
            premises = {o.get("content") for o in ops if o.get("kind") == "premise"}
            assert not (axioms & premises), (
                f"level {level} item {i} declares {axioms & premises} as both "
                "axiom and ordinary premise")


def test_preferences_never_assert_both_directions():
    """`p > q` together with `q > p` is legal -- the ordering is a preorder, so
    it reads as a tie -- but it is ungated, uncounted, and unexplained by the
    prompt, so it should not be generated by accident."""
    for task in ("status_query", "perturbation_prediction"):
        ds = create_dataset(task, size=3, level=10, seed=1, with_content=True)
        for i in range(3):
            prefs = {
                (o["kind"], o.get("stronger"), o.get("weaker"))
                for o in ds[i]["metadata"]["ops"]
                if str(o.get("kind", "")).startswith("prefer_")
            }
            reversed_pairs = [(k, a, b) for (k, a, b) in prefs if (k, b, a) in prefs]
            assert not reversed_pairs, (
                f"{task} item {i} asserts both directions: {reversed_pairs}")


def test_gold_still_self_scores_after_the_fixes():
    """Guard against a well-formedness fix quietly breaking gold."""
    for task in ("claim_identification", "formalization", "status_query"):
        for with_content in (False, True):
            ds = create_dataset(task, size=2, level=5, seed=3,
                                with_content=with_content)
            for i in range(2):
                entry = ds[i]
                ok, reasons = validate_entry(entry)
                assert ok, f"{task} item {i} failed validation: {reasons}"
                assert score_answer(entry["answer"], entry) >= 0.999
